// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmQ3ktaAwRVZ199GUWtfNTWo29VKNTeg',
    appId: '1:353775270960:web:1c58544484c398892f01f5',
    messagingSenderId: '353775270960',
    projectId: 'diplomchatapp',
    authDomain: 'diplomchatapp.firebaseapp.com',
    storageBucket: 'diplomchatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIcrmTuVkUUxKvy5sxGtaxTSPhZPcWfTs',
    appId: '1:353775270960:android:79597831464d82192f01f5',
    messagingSenderId: '353775270960',
    projectId: 'diplomchatapp',
    storageBucket: 'diplomchatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlfTNDtW7YT-WlQ6anp_TccJPu2BNhZU',
    appId: '1:353775270960:ios:1578454305cfd3a32f01f5',
    messagingSenderId: '353775270960',
    projectId: 'diplomchatapp',
    storageBucket: 'diplomchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlfTNDtW7YT-WlQ6anp_TccJPu2BNhZU',
    appId: '1:353775270960:ios:1578454305cfd3a32f01f5',
    messagingSenderId: '353775270960',
    projectId: 'diplomchatapp',
    storageBucket: 'diplomchatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatapptute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYmQ3ktaAwRVZ199GUWtfNTWo29VKNTeg',
    appId: '1:353775270960:web:91b5e0d4ac93a3d02f01f5',
    messagingSenderId: '353775270960',
    projectId: 'diplomchatapp',
    authDomain: 'diplomchatapp.firebaseapp.com',
    storageBucket: 'diplomchatapp.firebasestorage.app',
  );
}
